# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/andrea/sources/c/tritedb

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/andrea/sources/c/tritedb

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/andrea/sources/c/tritedb/CMakeFiles /home/andrea/sources/c/tritedb/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/andrea/sources/c/tritedb/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named tritedb_test

# Build rule for target.
tritedb_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tritedb_test
.PHONY : tritedb_test

# fast build rule for target.
tritedb_test/fast:
	$(MAKE) -f CMakeFiles/tritedb_test.dir/build.make CMakeFiles/tritedb_test.dir/build
.PHONY : tritedb_test/fast

#=============================================================================
# Target rules for targets named tritedb

# Build rule for target.
tritedb: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tritedb
.PHONY : tritedb

# fast build rule for target.
tritedb/fast:
	$(MAKE) -f CMakeFiles/tritedb.dir/build.make CMakeFiles/tritedb.dir/build
.PHONY : tritedb/fast

src/config.o: src/config.c.o

.PHONY : src/config.o

# target to build an object file
src/config.c.o:
	$(MAKE) -f CMakeFiles/tritedb_test.dir/build.make CMakeFiles/tritedb_test.dir/src/config.c.o
	$(MAKE) -f CMakeFiles/tritedb.dir/build.make CMakeFiles/tritedb.dir/src/config.c.o
.PHONY : src/config.c.o

src/config.i: src/config.c.i

.PHONY : src/config.i

# target to preprocess a source file
src/config.c.i:
	$(MAKE) -f CMakeFiles/tritedb_test.dir/build.make CMakeFiles/tritedb_test.dir/src/config.c.i
	$(MAKE) -f CMakeFiles/tritedb.dir/build.make CMakeFiles/tritedb.dir/src/config.c.i
.PHONY : src/config.c.i

src/config.s: src/config.c.s

.PHONY : src/config.s

# target to generate assembly for a file
src/config.c.s:
	$(MAKE) -f CMakeFiles/tritedb_test.dir/build.make CMakeFiles/tritedb_test.dir/src/config.c.s
	$(MAKE) -f CMakeFiles/tritedb.dir/build.make CMakeFiles/tritedb.dir/src/config.c.s
.PHONY : src/config.c.s

src/list.o: src/list.c.o

.PHONY : src/list.o

# target to build an object file
src/list.c.o:
	$(MAKE) -f CMakeFiles/tritedb_test.dir/build.make CMakeFiles/tritedb_test.dir/src/list.c.o
	$(MAKE) -f CMakeFiles/tritedb.dir/build.make CMakeFiles/tritedb.dir/src/list.c.o
.PHONY : src/list.c.o

src/list.i: src/list.c.i

.PHONY : src/list.i

# target to preprocess a source file
src/list.c.i:
	$(MAKE) -f CMakeFiles/tritedb_test.dir/build.make CMakeFiles/tritedb_test.dir/src/list.c.i
	$(MAKE) -f CMakeFiles/tritedb.dir/build.make CMakeFiles/tritedb.dir/src/list.c.i
.PHONY : src/list.c.i

src/list.s: src/list.c.s

.PHONY : src/list.s

# target to generate assembly for a file
src/list.c.s:
	$(MAKE) -f CMakeFiles/tritedb_test.dir/build.make CMakeFiles/tritedb_test.dir/src/list.c.s
	$(MAKE) -f CMakeFiles/tritedb.dir/build.make CMakeFiles/tritedb.dir/src/list.c.s
.PHONY : src/list.c.s

src/main.o: src/main.c.o

.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) -f CMakeFiles/tritedb.dir/build.make CMakeFiles/tritedb.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) -f CMakeFiles/tritedb.dir/build.make CMakeFiles/tritedb.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) -f CMakeFiles/tritedb.dir/build.make CMakeFiles/tritedb.dir/src/main.c.s
.PHONY : src/main.c.s

src/network.o: src/network.c.o

.PHONY : src/network.o

# target to build an object file
src/network.c.o:
	$(MAKE) -f CMakeFiles/tritedb_test.dir/build.make CMakeFiles/tritedb_test.dir/src/network.c.o
	$(MAKE) -f CMakeFiles/tritedb.dir/build.make CMakeFiles/tritedb.dir/src/network.c.o
.PHONY : src/network.c.o

src/network.i: src/network.c.i

.PHONY : src/network.i

# target to preprocess a source file
src/network.c.i:
	$(MAKE) -f CMakeFiles/tritedb_test.dir/build.make CMakeFiles/tritedb_test.dir/src/network.c.i
	$(MAKE) -f CMakeFiles/tritedb.dir/build.make CMakeFiles/tritedb.dir/src/network.c.i
.PHONY : src/network.c.i

src/network.s: src/network.c.s

.PHONY : src/network.s

# target to generate assembly for a file
src/network.c.s:
	$(MAKE) -f CMakeFiles/tritedb_test.dir/build.make CMakeFiles/tritedb_test.dir/src/network.c.s
	$(MAKE) -f CMakeFiles/tritedb.dir/build.make CMakeFiles/tritedb.dir/src/network.c.s
.PHONY : src/network.c.s

src/protocol.o: src/protocol.c.o

.PHONY : src/protocol.o

# target to build an object file
src/protocol.c.o:
	$(MAKE) -f CMakeFiles/tritedb_test.dir/build.make CMakeFiles/tritedb_test.dir/src/protocol.c.o
	$(MAKE) -f CMakeFiles/tritedb.dir/build.make CMakeFiles/tritedb.dir/src/protocol.c.o
.PHONY : src/protocol.c.o

src/protocol.i: src/protocol.c.i

.PHONY : src/protocol.i

# target to preprocess a source file
src/protocol.c.i:
	$(MAKE) -f CMakeFiles/tritedb_test.dir/build.make CMakeFiles/tritedb_test.dir/src/protocol.c.i
	$(MAKE) -f CMakeFiles/tritedb.dir/build.make CMakeFiles/tritedb.dir/src/protocol.c.i
.PHONY : src/protocol.c.i

src/protocol.s: src/protocol.c.s

.PHONY : src/protocol.s

# target to generate assembly for a file
src/protocol.c.s:
	$(MAKE) -f CMakeFiles/tritedb_test.dir/build.make CMakeFiles/tritedb_test.dir/src/protocol.c.s
	$(MAKE) -f CMakeFiles/tritedb.dir/build.make CMakeFiles/tritedb.dir/src/protocol.c.s
.PHONY : src/protocol.c.s

src/ringbuf.o: src/ringbuf.c.o

.PHONY : src/ringbuf.o

# target to build an object file
src/ringbuf.c.o:
	$(MAKE) -f CMakeFiles/tritedb_test.dir/build.make CMakeFiles/tritedb_test.dir/src/ringbuf.c.o
	$(MAKE) -f CMakeFiles/tritedb.dir/build.make CMakeFiles/tritedb.dir/src/ringbuf.c.o
.PHONY : src/ringbuf.c.o

src/ringbuf.i: src/ringbuf.c.i

.PHONY : src/ringbuf.i

# target to preprocess a source file
src/ringbuf.c.i:
	$(MAKE) -f CMakeFiles/tritedb_test.dir/build.make CMakeFiles/tritedb_test.dir/src/ringbuf.c.i
	$(MAKE) -f CMakeFiles/tritedb.dir/build.make CMakeFiles/tritedb.dir/src/ringbuf.c.i
.PHONY : src/ringbuf.c.i

src/ringbuf.s: src/ringbuf.c.s

.PHONY : src/ringbuf.s

# target to generate assembly for a file
src/ringbuf.c.s:
	$(MAKE) -f CMakeFiles/tritedb_test.dir/build.make CMakeFiles/tritedb_test.dir/src/ringbuf.c.s
	$(MAKE) -f CMakeFiles/tritedb.dir/build.make CMakeFiles/tritedb.dir/src/ringbuf.c.s
.PHONY : src/ringbuf.c.s

src/server.o: src/server.c.o

.PHONY : src/server.o

# target to build an object file
src/server.c.o:
	$(MAKE) -f CMakeFiles/tritedb_test.dir/build.make CMakeFiles/tritedb_test.dir/src/server.c.o
	$(MAKE) -f CMakeFiles/tritedb.dir/build.make CMakeFiles/tritedb.dir/src/server.c.o
.PHONY : src/server.c.o

src/server.i: src/server.c.i

.PHONY : src/server.i

# target to preprocess a source file
src/server.c.i:
	$(MAKE) -f CMakeFiles/tritedb_test.dir/build.make CMakeFiles/tritedb_test.dir/src/server.c.i
	$(MAKE) -f CMakeFiles/tritedb.dir/build.make CMakeFiles/tritedb.dir/src/server.c.i
.PHONY : src/server.c.i

src/server.s: src/server.c.s

.PHONY : src/server.s

# target to generate assembly for a file
src/server.c.s:
	$(MAKE) -f CMakeFiles/tritedb_test.dir/build.make CMakeFiles/tritedb_test.dir/src/server.c.s
	$(MAKE) -f CMakeFiles/tritedb.dir/build.make CMakeFiles/tritedb.dir/src/server.c.s
.PHONY : src/server.c.s

src/trie.o: src/trie.c.o

.PHONY : src/trie.o

# target to build an object file
src/trie.c.o:
	$(MAKE) -f CMakeFiles/tritedb_test.dir/build.make CMakeFiles/tritedb_test.dir/src/trie.c.o
	$(MAKE) -f CMakeFiles/tritedb.dir/build.make CMakeFiles/tritedb.dir/src/trie.c.o
.PHONY : src/trie.c.o

src/trie.i: src/trie.c.i

.PHONY : src/trie.i

# target to preprocess a source file
src/trie.c.i:
	$(MAKE) -f CMakeFiles/tritedb_test.dir/build.make CMakeFiles/tritedb_test.dir/src/trie.c.i
	$(MAKE) -f CMakeFiles/tritedb.dir/build.make CMakeFiles/tritedb.dir/src/trie.c.i
.PHONY : src/trie.c.i

src/trie.s: src/trie.c.s

.PHONY : src/trie.s

# target to generate assembly for a file
src/trie.c.s:
	$(MAKE) -f CMakeFiles/tritedb_test.dir/build.make CMakeFiles/tritedb_test.dir/src/trie.c.s
	$(MAKE) -f CMakeFiles/tritedb.dir/build.make CMakeFiles/tritedb.dir/src/trie.c.s
.PHONY : src/trie.c.s

src/util.o: src/util.c.o

.PHONY : src/util.o

# target to build an object file
src/util.c.o:
	$(MAKE) -f CMakeFiles/tritedb_test.dir/build.make CMakeFiles/tritedb_test.dir/src/util.c.o
	$(MAKE) -f CMakeFiles/tritedb.dir/build.make CMakeFiles/tritedb.dir/src/util.c.o
.PHONY : src/util.c.o

src/util.i: src/util.c.i

.PHONY : src/util.i

# target to preprocess a source file
src/util.c.i:
	$(MAKE) -f CMakeFiles/tritedb_test.dir/build.make CMakeFiles/tritedb_test.dir/src/util.c.i
	$(MAKE) -f CMakeFiles/tritedb.dir/build.make CMakeFiles/tritedb.dir/src/util.c.i
.PHONY : src/util.c.i

src/util.s: src/util.c.s

.PHONY : src/util.s

# target to generate assembly for a file
src/util.c.s:
	$(MAKE) -f CMakeFiles/tritedb_test.dir/build.make CMakeFiles/tritedb_test.dir/src/util.c.s
	$(MAKE) -f CMakeFiles/tritedb.dir/build.make CMakeFiles/tritedb.dir/src/util.c.s
.PHONY : src/util.c.s

tests/structures_test.o: tests/structures_test.c.o

.PHONY : tests/structures_test.o

# target to build an object file
tests/structures_test.c.o:
	$(MAKE) -f CMakeFiles/tritedb_test.dir/build.make CMakeFiles/tritedb_test.dir/tests/structures_test.c.o
.PHONY : tests/structures_test.c.o

tests/structures_test.i: tests/structures_test.c.i

.PHONY : tests/structures_test.i

# target to preprocess a source file
tests/structures_test.c.i:
	$(MAKE) -f CMakeFiles/tritedb_test.dir/build.make CMakeFiles/tritedb_test.dir/tests/structures_test.c.i
.PHONY : tests/structures_test.c.i

tests/structures_test.s: tests/structures_test.c.s

.PHONY : tests/structures_test.s

# target to generate assembly for a file
tests/structures_test.c.s:
	$(MAKE) -f CMakeFiles/tritedb_test.dir/build.make CMakeFiles/tritedb_test.dir/tests/structures_test.c.s
.PHONY : tests/structures_test.c.s

tests/trie_test.o: tests/trie_test.c.o

.PHONY : tests/trie_test.o

# target to build an object file
tests/trie_test.c.o:
	$(MAKE) -f CMakeFiles/tritedb_test.dir/build.make CMakeFiles/tritedb_test.dir/tests/trie_test.c.o
.PHONY : tests/trie_test.c.o

tests/trie_test.i: tests/trie_test.c.i

.PHONY : tests/trie_test.i

# target to preprocess a source file
tests/trie_test.c.i:
	$(MAKE) -f CMakeFiles/tritedb_test.dir/build.make CMakeFiles/tritedb_test.dir/tests/trie_test.c.i
.PHONY : tests/trie_test.c.i

tests/trie_test.s: tests/trie_test.c.s

.PHONY : tests/trie_test.s

# target to generate assembly for a file
tests/trie_test.c.s:
	$(MAKE) -f CMakeFiles/tritedb_test.dir/build.make CMakeFiles/tritedb_test.dir/tests/trie_test.c.s
.PHONY : tests/trie_test.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... tritedb_test"
	@echo "... rebuild_cache"
	@echo "... tritedb"
	@echo "... src/config.o"
	@echo "... src/config.i"
	@echo "... src/config.s"
	@echo "... src/list.o"
	@echo "... src/list.i"
	@echo "... src/list.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/network.o"
	@echo "... src/network.i"
	@echo "... src/network.s"
	@echo "... src/protocol.o"
	@echo "... src/protocol.i"
	@echo "... src/protocol.s"
	@echo "... src/ringbuf.o"
	@echo "... src/ringbuf.i"
	@echo "... src/ringbuf.s"
	@echo "... src/server.o"
	@echo "... src/server.i"
	@echo "... src/server.s"
	@echo "... src/trie.o"
	@echo "... src/trie.i"
	@echo "... src/trie.s"
	@echo "... src/util.o"
	@echo "... src/util.i"
	@echo "... src/util.s"
	@echo "... tests/structures_test.o"
	@echo "... tests/structures_test.i"
	@echo "... tests/structures_test.s"
	@echo "... tests/trie_test.o"
	@echo "... tests/trie_test.i"
	@echo "... tests/trie_test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

